
import { GoogleGenAI } from "@google/genai";

export interface StructuredPaper {
  title: string;
  authors: string[];
  abstract: string;
  keywords: string[];
  sections: Array<{ heading: string; level: number; content: string }>;
  references: string[];
}

/**
 * Uses Gemini to identify the structural components of the paper
 * without altering any of the original text content.
 */
export const parsePaperStructure = async (text: string): Promise<StructuredPaper> => {
  // Always create a new GoogleGenAI instance right before making an API call.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-preview',
    contents: `Identify and extract the following sections from the research paper text. 
    IMPORTANT: Do NOT change any words, do NOT summarize, and do NOT correct grammar. 
    Strictly maintain all original text.
    
    Format the response as a valid JSON object:
    {
      "title": "Exact title from text",
      "authors": ["Full author list strings"],
      "abstract": "The exact abstract text",
      "keywords": ["List of keywords if found"],
      "sections": [{"heading": "SECTION NAME", "level": 1, "content": "Full section text..."}],
      "references": ["Reference list strings"]
    }

    Paper Text:
    ${text}`,
    config: {
      responseMimeType: "application/json",
      thinkingConfig: { thinkingBudget: 24576 }
    }
  });

  const parsed = JSON.parse(response.text || '{}');
  return parsed as StructuredPaper;
};

/**
 * Performs a search-grounded query for the AI Assistant.
 */
export const searchGroundingQuery = async (query: string) => {
  // Create a new GoogleGenAI instance for each call.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: query,
    config: {
      tools: [{ googleSearch: {} }],
    },
  });
  return {
    text: response.text || '',
    sources: response.candidates?.[0]?.groundingMetadata?.groundingChunks || []
  };
};

/**
 * Analyzes paper content or provides general reasoning using advanced reasoning capabilities.
 */
export const analyzePaperContent = async (query: string) => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-preview',
    contents: query,
    config: {
      thinkingConfig: { thinkingBudget: 16384 }
    }
  });
  return response.text;
};

/**
 * Generates a scientific figure based on a descriptive prompt.
 */
export const generatePaperFigure = async (prompt: string, size: "1K" | "2K" | "4K" = "1K") => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: {
      parts: [
        {
          text: `Scientific figure for an IEEE journal paper: ${prompt}. Style: Clean, high-contrast, professional academic publication quality.`,
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1",
        imageSize: size
      }
    }
  });

  // Iterate through all parts to find the image data.
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      const base64EncodeString: string = part.inlineData.data;
      return `data:image/png;base64,${base64EncodeString}`;
    }
  }
  throw new Error("No image was generated by the model.");
};

/**
 * Analyzes an uploaded image, such as a plot or chart, for scientific context.
 */
export const analyzeUploadedImage = async (base64: string, mimeType: string) => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64,
            mimeType: mimeType,
          },
        },
        {
          text: 'Analyze this image in the context of a scientific paper. Extract key observations, explain the data if it is a graph, and relate it to IEEE publication standards.',
        },
      ],
    },
  });
  return response.text;
};
